Se agrega soporte para FEE
CRLibre/API_Hacienda pull request #164
Opened 2024-04-02 13:56 UTC by sayerpro

Se agrega funcionalidad en el API para trabajar con comprobantes de FEE(Factura electrónica de exportación) se crea este pull request bajo la supervicion y atención de Jean y francisco como Reviewers. Adicionalmente se deja datos para consumo de creación de XML vía POSTMAN:

w:genXML
r:gen_xml_fee
clave:50627032400020536006000100001090000000020100000020
codigo_actividad:210201
consecutivo:00100001090000000020
fecha_emision:2024-03-27T12:00:00-06:00
emisor_nombre:Nombre completo emisor
emisor_tipo_identif:01
emisor_num_identif:123456789
//emisor_nombre_comercial:Nombre comercial emisor
emisor_provincia:2
emisor_canton:12
emisor_distrito:04
//emisor_barrio:01
emisor_otras_senas:Descricion lugar de ubicacion
//emisor_cod_pais_tel:506
//emisor_tel:1234567
//emisor_cod_pais_fax:506
//emisor_fax:00000000
emisor_email:correo@ejemplo.com
//receptor_nombre:Walner Borbon
//receptor_tipo_identif:01
//receptor_num_identif:702320717
//receptor_identif_extranjero:123
//receptor_nombre_comercial:Walner
//receptor_otras_senas_extranjero:en el arbolete
//receptor_cod_pais_tel:506
//receptor_tel:84922891
//receptor_cod_pais_fax:506
//receptor_fax:00000000
//receptor_email:walner.borbon@hotmail.com
condicion_venta:01
//plazo_credito:0
medio_pago:{"medioPago":["01"]}
detalles:{"1":{"cantidad":"1","codigo":"1234567890123","codigoComercial":{"1":{"codigo":"123","tipo":"01"}},"descuento":{"1":{"montoDescuento":"123","naturalezaDescuento":"Me cayo bien"}},"detalle":"Habitacion alquilada","impuesto":{"1":{"codigo":"01","CodigoTarifa":"01","factorIVA":"123","monto":"1170","montoExportacion":"123","tarifa":"11.7"}},"impuestoNeto":"123","montoTotal":"123","montoTotalLinea":"123","partidaArancelaria":"123456789012","precioUnitario":"123","subTotal":"123","unidadMedida":"Al","unidadMedidaComercial":"Al"},"2":{"cantidad":"1","codigo":"1234567890123","codigoComercial":{"1":{"codigo":"123","tipo":"01"}},"descuento":{"1":{"montoDescuento":"123","naturalezaDescuento":"Me cayo bien"}},"detalle":"Habitacion alquilada","impuesto":{"1":{"codigo":"01","CodigoTarifa":"01","factorIVA":"123","monto":"1170","montoExportacion":"123","tarifa":"11.7"}},"impuestoNeto":"123","montoTotal":"123","montoTotalLinea":"123","partidaArancelaria":"123456789012","precioUnitario":"123","subTotal":"123","unidadMedida":"Al","unidadMedidaComercial":"Al"}}
//otrosCargos:01
//cod_moneda:CRC
//tipo_cambio:564.48
//total_serv_gravados:0
//total_serv_exentos:10000
//total_merc_gravada:10000
//total_merc_exenta:0
//total_gravados:10000
//total_exento:10000
total_ventas:20000
//total_descuentos:100
total_ventas_neta:19900
//total_impuestos:1170
//totalOtrosCargos:20000
total_comprobante:21070
//infoRefeTipoDoc:01
//infoRefeNumero:50620032400020536006000100001010000000017100000017
//infoRefeFechaEmision:2024-03-19T12:00:00-06:00
//infoRefeCodigo:01
//infoRefeRazon:Falta de informacion
//otros:{"otroContenido":[{"codigo":"CONT1","contenidoEstructurado":{"Elemento1":"Contenido 1","Elemento2":"Contenido 2"}}],"otroTexto":{"codigo":"COD1","texto":"Texto opcional 1"}}

Todos los datos aqui los maneja el FEE acorde al (FacturaElectronicaExportacion_V4.3.xsd) del ministerio de hacienda, los campos con '//' son opcionales.

2024-04-08 14:16 UTC, JeanCarlosChavarriaHughes commented
@sayerpro 
Hola, revisando los cambios del PR, no veo cambios en el archivo check.php:
https://github.com/sayerpro/API_Hacienda/blob/SoporteFEE/api/contrib/check/check.php

Me parece que es necesario tambien agregar el nuevo tipo FEE 09, a este archivo, similar a como se hizo en este otro PR de referencia?
https://github.com/CRLibre/API_Hacienda/pull/163/files#diff-b185aad9880acae398a11f6289cb618b6b79d4b4118eb71d19ceefe3570b9957

2024-04-08 14:40 UTC, JeanCarlosChavarriaHughes requested changes
Please review the comments.

2024-04-08 14:40 UTC, JeanCarlosChavarriaHughes commented on api/contrib/genXML/genXML.php
> +    $receptorEmail                  = params_get("receptor_email");
@sayerpro 
Parece que hace falta el campo `omitir_receptor`, `mediosPago`, `otrosType` , tal vez tambien otros campos que se han agregados en los otros encabezados.

```
  $omitir_receptor                = params_get("omitir_receptor");
  $mediosPago                     = json_decode(params_get("medios_pago"));
  $otrosType                      = params_get("otrosType");
```

2024-04-08 14:40 UTC, JeanCarlosChavarriaHughes commented on api/contrib/genXML/genXML.php
> +    $receptorEmail                  = params_get("receptor_email");
Esto tambien afectaría el otro module.php
 https://github.com/CRLibre/API_Hacienda/pull/164/files#diff-d31beb9115eb3ad9a88d20daca7313ad63050bfea226d00ba6f4d3267595162a

2024-04-08 14:40 UTC, JeanCarlosChavarriaHughes commented on api/contrib/genXML/module.php
> +            'params' => array(
No se agregaron parámetros que podrían ser empleados en ciertas circunstancias. 
```
 $omitir_receptor                = params_get("omitir_receptor");
  $mediosPago                     = json_decode(params_get("medios_pago"));
  $otrosType                      = params_get("otrosType");
```

2024-04-08 14:40 UTC, JeanCarlosChavarriaHughes commented on api/contrib/genXML/genXML.php
En la línea 22. Parece que hace falta agregar el código de documento 09:

actual
`const TIPODOCREFVALUES = array('01','02','03','04','05','06','07','08','99');`

esperado
`const TIPODOCREFVALUES = array('01','02','03','04','05','06','07','08','09','99');`

por favor, confirmar.

2024-04-08 20:08 UTC, sayerpro commented on api/contrib/genXML/genXML.php
> +    $receptorEmail                  = params_get("receptor_email");
Hola Jean, muchas gracias por las revisiones.

El campo omitir receptor lo quite, dado que considere que si no era necesario el receptor, no se deberia enviar dato alguno del mismo.

El campo otrosType, tambien se quito dado que ahora funciona como un JSON, que se trata en la linea 3485; EN la linea 3468 se puede ver el JSON de ejemplo de como podría enviarse, ya no se envia uno solo si es uno, o otrostype si son varios, si no que ahora se envia lo necesario en un solo JSON.

El campo mediosPago se cambio tambien a un JSON, dado que este elemento puede ser mas de 1 hasta un maximo de 4, ahora si solo se necesita uno, se envia uno en el JSON y no se hace separado como se hacia anteriormente.

Conclusion:
- omitir_receptor | dejo de existir (si no se reuiqere receptor ¿para que enviarlo?)
- mediosPago | cambio a JSON, ya que anteriormente se enviaba un campo si solo era uno, y otro campo si eran varios se unifico y quedo en un JSON, se puede ver el tratado de este en la linea 3197 hasta la 3216
- otros_type | dejo de existir dado que ahora se unifica la estructura del campo otros en un solo JSON desde la linea 3468 hasta la linea  3516

En caso de considerar cambiar nuevamente los campos para que sactisfagan estos controles que mencionas, he de cambiar el código nuevamente, sin embargo la funcionalidad de la creación del XML FEE no es erronea, solo cambio la manera en como se envia estos 3 Datos.

2024-04-08 20:08 UTC, sayerpro commented on api/contrib/genXML/module.php
> +            'params' => array(
Estos campos dejaron de existir.

- omitir_receptor  | si se va a omitir el receptor entonces para que enviar información del mismo?
- mediosPago | dejo de existir y ahora solo se maneja un campo llamado medio_pago que recibe un JSON
- otrosType | dejo de existir y se unifico en un JSON llamado otros

En caso de considerar cambiar nuevamente los campos para que sactisfagan estos controles que mencionas, he de cambiar el código nuevamente, sin embargo la funcionalidad de la creación del XML FEE no es erronea, solo cambio la manera en como se envia estos 3 Datos.

2024-04-08 20:08 UTC, sayerpro commented on api/contrib/genXML/genXML.php
Gracias por la revisión, ya mismo agrego el campo faltante tal y como indicas que ha de ser esperado.

2024-04-08 20:08 UTC, sayerpro commented
Los archivos (check.php y xmlGenerator.php) salieron de mi esfera/mapa de alcance ya que no vi que se usaran en logica alguna cuando entra a recorrer el código para la generación del XML (o quizas no preste suficiente atención). Igualmente ya les he agregado el soporte en base a las guis ofrecidas.

2024-04-18 01:26 UTC, JeanCarlosChavarriaHughes commented
La funcionalidad de generar el XML para el tipo de comprobante: 
- Factura Electronica de Exportación (FEE)
Fue agregada y verificada satisfactoriamente.

Ejemplo del Request empleado para la generación:
```
curl --location 'http://127.0.0.1:8080/api.php' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'w=genXML' \
--data-urlencode 'r=gen_xml_fee' \
--data-urlencode 'clave=50610012400011520039900100020010000000003187435126' \
--data-urlencode 'codigo_actividad=552001' \
--data-urlencode 'consecutivo=00100020010000000003' \
--data-urlencode 'fecha_emision=2024-01-24T11:16:56-06:00' \
--data-urlencode 'emisor_nombre=DANIEL' \
--data-urlencode 'emisor_tipo_identif=01' \
--data-urlencode 'emisor_num_identif=115000300' \
--data-urlencode 'emisor_nombre_comercial=Daniel' \
--data-urlencode 'emisor_provincia=1' \
--data-urlencode 'emisor_canton=15' \
--data-urlencode 'emisor_distrito=01' \
--data-urlencode 'emisor_barrio=01' \
--data-urlencode 'emisor_otras_senas=PATIO DE AGUA' \
--data-urlencode 'emisor_cod_pais_tel=506' \
--data-urlencode 'emisor_tel=87000000' \
--data-urlencode 'emisor_cod_pais_fax=506' \
--data-urlencode 'emisor_fax=87000000' \
--data-urlencode 'emisor_email=ejemplo@gmail.com' \
--data-urlencode 'receptor_nombre=DOS SOCIEDAD ANONIMA' \
--data-urlencode 'receptor_tipo_identif=02' \
--data-urlencode 'receptor_num_identif=3101070000' \
--data-urlencode 'receptor_provincia=4' \
--data-urlencode 'receptor_canton=01' \
--data-urlencode 'receptor_distrito=04' \
--data-urlencode 'receptor_barrio=01' \
--data-urlencode 'receptor_cod_pais_tel=506' \
--data-urlencode 'receptor_tel=22000000' \
--data-urlencode 'receptor_email=receptor@hotmail.com' \
--data-urlencode 'condicion_venta=01' \
--data-urlencode 'plazo_credito=0' \
--data-urlencode 'cod_moneda=USD' \
--data-urlencode 'tipo_cambio=517.72' \
--data-urlencode 'total_serv_gravados=6800.00' \
--data-urlencode 'total_serv_exentos=0.00' \
--data-urlencode 'total_merc_gravada=0.00' \
--data-urlencode 'total_merc_exenta=0.00' \
--data-urlencode 'total_gravados=6800.00' \
--data-urlencode 'total_exento=0.00' \
--data-urlencode 'total_ventas=6800.00' \
--data-urlencode 'total_descuentos=0.00' \
--data-urlencode 'total_ventas_neta=6800.00' \
--data-urlencode 'total_impuestos=884.00' \
--data-urlencode 'total_comprobante=6800.00' \
--data-urlencode 'otros={"otroContenido":[{"codigo":"CONT1","contenidoEstructurado":{"Elemento1":"Contenido 1","Elemento2":"Contenido 2"}}],"otroTexto":{"codigo":"COD1","texto":"Texto opcional 1"}}

' \
--data-urlencode 'detalles={"1":{"cantidad":"1","codigo":"1234567890123","codigoComercial":{"1":{"codigo":"123","tipo":"01"}},"descuento":{"1":{"montoDescuento":"123","naturalezaDescuento":"Me cayo bien"}},"detalle":"Habitacion alquilada","impuesto":{"1":{"codigo":"01","codigoTarifa":"01","factorIVA":"123","monto":"1170","montoExportacion":"123","tarifa":"11.7"}},"impuestoNeto":"123","montoTotal":"123","montoTotalLinea":"123","partidaArancelaria":"123456789012","precioUnitario":"123","subTotal":"123","unidadMedida":"Al","unidadMedidaComercial":"Al"},"2":{"cantidad":"1","codigo":"1234567890123","codigoComercial":{"1":{"codigo":"123","tipo":"01"}},"descuento":{"1":{"montoDescuento":"123","naturalezaDescuento":"Me cayo bien"}},"detalle":"Habitacion alquilada","impuesto":{"1":{"codigo":"01","codigoTarifa":"01","factorIVA":"123","monto":"1170","montoExportacion":"123","tarifa":"11.7"}},"impuestoNeto":"123","montoTotal":"123","montoTotalLinea":"123","partidaArancelaria":"123456789012","precioUnitario":"123","subTotal":"123","unidadMedida":"Al","unidadMedidaComercial":"Al"}}' \
--data-urlencode 'medio_pago={"medioPago":["01"]}' \
--data-urlencode 'otrosCargos={"otrosCargos":[{"detalle":"123","montoCargo":"123","porcentaje":"123","tipoDocumento":"01"}]}' \
--data-urlencode 'totalOtrosCargos=0.00' \
--data-urlencode 'infoRefeTipoDoc=01' \
--data-urlencode 'infoRefeNumero=50620032400020536006000100001010000000017100000017' \
--data-urlencode 'infoRefeFechaEmision=2024-04-02T12:00:00-06:00' \
--data-urlencode 'infoRefeCodigo=01' \
--data-urlencode 'infoRefeRazon=Falta informacion'```

2024-04-18 01:26 UTC, merged